	FW_DIR	:= /lib/firmware

all:
	cp -f rtl8761au_fw	 $(FW_DIR)/rtl8761au_fw
	cp -f rtl8761aw8192eu_fw $(FW_DIR)/rtl8761aw8192eu_fw
	cp -f rtl8761au8192ee_fw $(FW_DIR)/rtl8761au8192ee_fw
	cp -f rtl8761au8812ae_fw $(FW_DIR)/rtl8761au8812ae_fw

clean:
	rm -f $(FW_DIR)/rtl8761au_fw
	rm -f $(FW_DIR)/rtl8761aw8192eu_fw
	rm -f $(FW_DIR)/rtl8761au8192ee_fw
	rm -f $(FW_DIR)/rtl8761au8812ae_fw

